project:
  type: website

website:
  title: "Nosy Whale"
  navbar:
    tools:
      - icon: github
        menu:
          - text: Source Code
            url: https://github.com/NosyShark/NosyWhale/tree/main
      - icon: instagram
        menu:
          - text: Connect
            url: https://www.instagram.com/emmiswann/
  sidebar:
    style: "floating"
    search: true
    contents: 
      - section: "About the Author"
        contents:
          - index.qmd
      - section: "Current Work"
        contents:
          - shyshark.qmd
      - section: "Book Reviews"
        contents:
          - lifechanging.qmd
          - silentearth.qmd
      - section: "Interesting Critters"
        contents:
          - 

          
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: 
      light: minty.css
      dark: darkminty.css
    css: styles.css
    toc: true

editor: visual

